name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install pnpm --global
          pnpm i

      - name: Archive lib artifacts
        if: startsWith(github.event.head_commit.message, 'release')
        uses: actions/upload-artifact@v4
        with:
          name: lib-dist
          path: |
            lib
            !lib/node_modules
  publish:
    needs: build
    if: startsWith(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Download lib artifacts
        uses: actions/download-artifact@v4
        with:
          name: lib-dist
      - name: Check files
        run: ls


